# Generated by Django 5.0.1 on 2024-02-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MenuHeadlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('teema', models.CharField(blank=True, max_length=255, null=True)),
                ('soovitab', models.CharField(blank=True, max_length=255, null=True)),
                ('valmistas', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'menuheadlines',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.category')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.menuheadlines')),
            ],
            options={
                'ordering': ['date', 'category_id'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=50)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('half_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_fooditem', to='app_admin.foodmenu')),
            ],
            options={
                'ordering': ['menu'],
            },
        ),
    ]
