# Generated by Django 4.2.7 on 2023-11-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuHeadlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('teema', models.CharField(max_length=255)),
                ('soovitab', models.CharField(max_length=255)),
                ('valmistas', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'menuheadlines',
                'ordering': ['date'],
            },
        ),
    ]
