# Generated by Django 5.0.1 on 2024-03-07 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.category'),
        ),
    ]
