# Generated by Django 5.0.3 on 2024-03-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_alter_foodmenu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food',
            field=models.CharField(max_length=255),
        ),
    ]
