# Generated by Django 4.2.7 on 2023-11-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_alter_menuheadlines_soovitab_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuheadlines',
            options={'ordering': ['-date'], 'verbose_name_plural': 'menuheadlines'},
        ),
        migrations.CreateModel(
            name='ToiduNimed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('half_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('show_menu', models.BooleanField(default=True)),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.category')),
            ],
            options={
                'ordering': ['-date', 'category_ID'],
            },
        ),
    ]
