# Generated by Django 4.2.7 on 2023-11-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_alter_menuheadlines_options_toidunimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toidunimed',
            name='food_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
